rm(list=ls())
library(tidyverse)
library("rtracklayer")
library("SummarizedExperiment")
# counts_GROseq_U2OS.txt是5.pepline_GROseq_U2OS.sh脚本最后得到的counts矩阵
# counts_GROseq_U2OS.txt is the counts matrix generated by the 5.pipeline_GROseq_U2OS.sh script.
counts_U2OS <- read.table("counts_GROseq_U2OS.txt",header = T)
counts_U2OS <- counts_U2OS[,c(1,6:ncol(counts_U2OS))]
colnames(counts_U2OS)[3:4] <- c("U2OS1","U2OS2")
counts_U2OS$U2OS <- rowMeans(counts_U2OS[3:4])
counts_all <- counts_U2OS[,c(1,2,5)]
geneid_efflen <- subset(counts_all,select = c("Geneid","Length"))
colnames(geneid_efflen) <- c("geneid","efflen")  
counts <- data.frame(U2OS=counts_all$U2OS)
rownames(counts) <- counts_all[,1]
efflen <- geneid_efflen[match(rownames(counts),
                              geneid_efflen$geneid),
                        "efflen"]

counts2TPM <- function(count=count, efflength=efflen){
  RPK <- count/(efflength/1000)   
  PMSC_rpk <- sum(RPK)/1e6        
  RPK/PMSC_rpk              
}  
tpm <- as.data.frame(apply(counts,2,counts2TPM))
colSums(tpm) 

keep_feature <- rowSums(counts>1)==1
table(keep_feature)  
counts_filt <- data.frame(U2OS=counts[keep_feature, ])
rownames(counts_filt) <- rownames(counts)[keep_feature]
tpm_filt <- data.frame(U2OS=tpm[keep_feature, ])
rownames(tpm_filt) <- rownames(tpm)[keep_feature]
tpm_filt$gene_id <- rownames(tpm_filt)

tpm_filt$ENSEMBL <- substring(tpm_filt$gene_id,1,15)

save(tpm_filt,file="GROseq_U2OS_tpm.Rdata")
